name: Deploy to Heroku (Git-based)
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository  # ✅ Step 1: Get the latest code
        uses: actions/checkout@v2

      - name: Install Heroku CLI  # ✅ Step 2: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh

      - name: Set up Python  # ✅ Step 3: Install Python dependencies
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies  # ✅ Step 4: Install required Python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set Heroku to Use Docker  # ✅ Step 5: Ensure Heroku uses a Docker container
        run: heroku stack:set container --app ${{ secrets.HEROKU_APP_NAME }}

      - name: Login to Heroku Container Registry  # ✅ Step 6: Authenticate with Heroku Container Registry
        run: |
          echo ${{ secrets.HEROKU_API_KEY }} | heroku container:login

      - name: Deploy to Heroku Using Docker  # ✅ Step 7: Build & Push the Docker image to Heroku
        run: heroku container:push web --app ${{ secrets.HEROKU_APP_NAME }}

      - name: Release the Image  # ✅ Step 8: Release the pushed Docker image
        run: heroku container:release web --app ${{ secrets.HEROKU_APP_NAME }}

      - name: Check Logs  # ✅ Step 9: Get live logs (for debugging)
        run: heroku logs --tail --app ${{ secrets.HEROKU_APP_NAME }}
        # there is no any email requre